version: "3.9"
name: na-hora

services: 
    pg_db:
        image: postgres:latest
        container_name: pg_db
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=na-hora
        volumes: 
            - pgdata:/data/postgres

volumes: 
    pgdata:
        driver: local