version: "3.9"

services:
  na_hora_pg:
    image: postgres:latest
    container_name: na_hora_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=na-hora
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
