// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	repositories5 "na-hora/api/internal/models/city/repositories"
	services5 "na-hora/api/internal/models/city/services"
	"na-hora/api/internal/models/company/repositories"
	"na-hora/api/internal/models/company/services"
	repositories4 "na-hora/api/internal/models/state/repositories"
	services4 "na-hora/api/internal/models/state/services"
	repositories3 "na-hora/api/internal/models/token/repositories"
	services3 "na-hora/api/internal/models/token/services"
	repositories2 "na-hora/api/internal/models/user/repositories"
	services2 "na-hora/api/internal/models/user/services"
)

// Injectors from wire.go:

func InitializeCompanyService(db *gorm.DB) services.CompanyServiceInterface {
	companyRepositoryInterface := repositories.GetCompanyRepository(db)
	companyServiceInterface := services.GetCompanyService(companyRepositoryInterface)
	return companyServiceInterface
}

func InitializeUserService(db *gorm.DB) services2.UserServiceInterface {
	userRepositoryInterface := repositories2.GetUserRepository(db)
	userServiceInterface := services2.GetUserService(userRepositoryInterface)
	return userServiceInterface
}

func InitializeTokenService(db *gorm.DB) services3.TokenServiceInterface {
	tokenRepositoryInterface := repositories3.GetTokenRepository(db)
	tokenServiceInterface := services3.GetTokenService(tokenRepositoryInterface)
	return tokenServiceInterface
}

func InitializeStateService(db *gorm.DB) services4.StateServiceInterface {
	stateRepositoryInterface := repositories4.GetStateRepository(db)
	stateServiceInterface := services4.GetStateService(stateRepositoryInterface)
	return stateServiceInterface
}

func InitializeCityService(db *gorm.DB) services5.CityServiceInterface {
	cityRepositoryInterface := repositories5.GetCityRepository(db)
	cityServiceInterface := services5.GetCityService(cityRepositoryInterface)
	return cityServiceInterface
}

// wire.go:

var CompanyServiceSet = wire.NewSet(repositories.GetCompanyRepository, services.GetCompanyService)

var UserServiceSet = wire.NewSet(repositories2.GetUserRepository, services2.GetUserService)

var TokenServiceSet = wire.NewSet(repositories3.GetTokenRepository, services3.GetTokenService)

var StateServiceSet = wire.NewSet(repositories4.GetStateRepository, services4.GetStateService)

var CityServiceSet = wire.NewSet(repositories5.GetCityRepository, services5.GetCityService)
